# Generated by Django 2.1 on 2020-07-13 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventStallUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(upload_to='media')),
                ('registeration_by', models.CharField(choices=[('phone_number', 'phone_number'), ('name', 'name')], max_length=20)),
                ('brand_logo', models.ImageField(upload_to='media')),
                ('main_page_background_type', models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=20)),
                ('main_page_background_url', models.CharField(max_length=200)),
                ('lobby_video_link', models.CharField(max_length=200)),
                ('lobby_background_type', models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=20)),
                ('lobby_background_url', models.CharField(max_length=200)),
                ('lobby_left_logo', models.ImageField(upload_to='media')),
                ('lobby_right_logo', models.ImageField(upload_to='media')),
                ('lobby_banner_link', models.CharField(max_length=200)),
                ('hall_title_1', models.CharField(max_length=200)),
                ('hall_title_2', models.CharField(max_length=200)),
                ('hall_title_3', models.CharField(max_length=200)),
                ('hall_title_4', models.CharField(max_length=200)),
                ('resource_1_name', models.CharField(max_length=200)),
                ('resource_1_link', models.CharField(max_length=200)),
                ('resource_2_name', models.CharField(max_length=200)),
                ('resource_2_link', models.CharField(max_length=200)),
                ('resource_3_name', models.CharField(max_length=200)),
                ('resource_3_link', models.CharField(max_length=200)),
                ('resource_4_name', models.CharField(max_length=200)),
                ('resource_4_link', models.CharField(max_length=200)),
                ('auditorium_youtube_name', models.CharField(max_length=200)),
                ('auditorium_keynote_track', models.CharField(max_length=200)),
                ('auditorium_background_image', models.CharField(max_length=200)),
                ('info_desk', models.CharField(max_length=200)),
                ('website_url', models.CharField(max_length=200)),
                ('hall_logo_left', models.ImageField(upload_to='media')),
                ('hall_logo_center', models.ImageField(upload_to='media')),
                ('hall_logo_right', models.ImageField(upload_to='media')),
                ('hall_background_image', models.CharField(max_length=200)),
                ('resource_ui_name', models.CharField(max_length=200)),
                ('social_lounge_name', models.CharField(max_length=200)),
                ('social_lounge_background_image', models.ImageField(upload_to='media')),
                ('validity_time', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29')], max_length=5)),
                ('zoom_account_name', models.CharField(blank=True, max_length=15, null=True)),
                ('zoom_password', models.CharField(blank=True, max_length=15, null=True)),
                ('login_url', models.CharField(blank=True, max_length=20, null=True)),
                ('login_background_image', models.ImageField(upload_to='dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Stalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_video_url', models.CharField(max_length=200)),
                ('stall_web_link', models.CharField(max_length=200)),
                ('stall_admin_link', models.CharField(max_length=200)),
                ('stall_image_link', models.CharField(max_length=200)),
                ('unique_url', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.OrganizerDetails')),
            ],
        ),
        migrations.CreateModel(
            name='StallZoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=20, null=True)),
                ('zoom_meeting_password', models.CharField(blank=True, max_length=20, null=True)),
                ('stall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Stalls')),
            ],
        ),
        migrations.AddField(
            model_name='eventstallusers',
            name='event_stall_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Stalls'),
        ),
        migrations.AddField(
            model_name='eventstallusers',
            name='organizer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.OrganizerDetails'),
        ),
    ]
