# Generated by Django 2.2 on 2020-09-19 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200919_1751'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_website', '0001_initial'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='analytics',
#            name='user_id',
#            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
#            preserve_default=False,
#        ),
#        migrations.AddField(
#            model_name='call_schedules',
#            name='stall_id',
#            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Stalls'),
#            preserve_default=False,
#        ),
#        migrations.AddField(
#            model_name='message',
#            name='author',
#            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to=settings.AUTH_USER_MODEL),
#            preserve_default=False,
#        ),
#        migrations.AddField(
#            model_name='message',
#            name='reciever',
#            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
#        ),
#        migrations.AddField(
#            model_name='notification',
#            name='author',
#            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
#        ),
#        migrations.AddField(
#            model_name='notification',
#            name='reciever',
#            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL),
#        ),
#        migrations.AddField(
#            model_name='partners_tab',
#            name='stall_id',
#            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
#            preserve_default=False,
#        ),
    ]
